#How much Grime is consumed to make a single unit of Alchemical Waste when cleaning an alchemical device.
#Range: > 1
grimePerWaste = 250
#At what percent full of Grime that alchemical devices start to lose Efficiency and gain Operation Time.
#Range: 1 ~ 100
grimePenaltyPoint = 50
#How many mB of Academic Slurry constitutes one experience point.
#Range: 1 ~ 1000
fluidPerXPPoint = 40
#How many experience points a Studying construct generates from simple study materials.
#Range: > 1
constructStudyExperienceSimple = 2
#How many experience points a Studying construct generates from advanced study materials.
#Range: > 2
constructStudyExperienceAdvanced = 6
#How many experience points a Studying construct generates from master study materials.
#Range: > 4
constructStudyExperienceMaster = 18
#The amount of Academic Slurry, in mB, consumed to perform Fixation on a first-order Admixture.
#Range: > 10
fixationBaseSlurryCost = 40
#The percent cost increase over base that higher order Admixtures take to perform Fixation. This cost increase is multiplicative.
#Range: > 10
fixationSlurryCompoundCost = 300
#The percent of the experience cost to perform Fixation that is reduced if the process fails.
#Range: 0 ~ 100
fixationFailureRefund = 70
#The baseline efficiency of an Alembic.
#Range: 1 ~ 100
alembicEfficiency = 30
#The time, in ticks, that it takes for an Alembic to process one object.
#Range: > 1
alembicOperationTime = 200
#The maximum Grime level of the Alembic. 
#Range: > 100
alembicGrimeMaximum = 24000
#The amount of Grime generated by a dram of materia that successfully distills.
#Range: > 0
alembicGrimeOnSuccess = 75
#The amount of Grime generated by a dram of materia that fails to distill.
#Range: > 0
alembicGrimeOnFailure = 10
#The baseline efficiency of a Distillery.
#Range: 1 ~ 100
distilleryEfficiency = 35
#The time, in ticks, that it takes for a Distillery to process one object.
#Range: > 1
distilleryOperationTime = 160
#The maximum Grime level of the Distillery. 
#Range: > 100
distilleryGrimeMaximum = 40000
#The amount of Grime generated by a dram of materia that successfully distills.
#Range: > 0
distilleryGrimeOnSuccess = 75
#The amount of Grime generated by a dram of materia that fails to distill.
#Range: > 0
distilleryGrimeOnFailure = 10
#The baseline efficiency of a Centrifuge.
#Range: 1 ~ 100
centrifugeEfficiency = 35
#The time, in ticks, that it takes for a Centrifuge to separate one admixture into component materia.
#Range: > 1
centrifugeOperationTime = 160
#The maximum Grime level of the Centrifuge. 
#Range: > 100
centrifugeGrimeMaximum = 40000
#The amount of Grime generated by an admixture that successfully separates in a Centrifuge.
#Range: > 0
centrifugeGrimeOnSuccess = 75
#The amount of Grime generated by an admixture that fails to separate in a Centrifuge.
#Range: > 0
centrifugeGrimeOnFailure = 10
#The baseline efficiency of a Fusery.
#Range: 1 ~ 100
fuseryEfficiency = 35
#The time, in ticks, that it takes for an Admixer to make one admixture from its component materia.
#Range: > 1
fuseryOperationTime = 160
#The maximum Grime level of the Fusery. 
#Range: > 100
fuseryGrimeMaximum = 40000
#The amount of Grime generated by an admixture that successfully combines in a Fusery.
#Range: > 0
fuseryGrimeOnSuccess = 75
#The amount of Grime generated by an admixture that fails to combine in a Fusery.
#Range: > 0
fuseryGrimeOnFailure = 10
#The amount of Academic Slurry, in mB, the Fusery's internal tank can hold.
#Range: > 500
fuseryTankCapacity = 4000
#The amount of Academic Slurry, in mB, the Alchemical Nexus's internal tank can hold.
#Range: > 500
alchemicalNexusTankCapacity = 12000
#How much FE/tick the Circle of Power generates when it has one reagent
#Range: > 1
circlePowerGen1 = 3
#How much FE/tick the Circle of Power generates when it has two reagents
#Range: > 2
circlePowerGen2 = 36
#How much FE/tick the Circle of Power generates when it has three reagents
#Range: > 3
circlePowerGen3 = 432
#How much FE/tick the Circle of Power generates when it has all four reagents
#Range: > 4
circlePowerGen4 = 5184
#How many ticks of activity the Circle of Power stores at once
#Range: 1 ~ 72000
circlePowerBuffer = 3
#How much of one type of Essentia can be stored inside of a Materia Jar.
#Range: > 64
materiaJarEssentiaCapacity = 360
#How much of one type of Admixture can be stored inside of a Materia Jar.
#Range: > 64
materiaJarAdmixtureCapacity = 180
#How much of one type of Essentia can be stored inside of a Materia Vessel.
#Range: > 64
materiaVesselEssentiaCapacity = 3600
#How much of one type of Admixture can be stored inside of a Materia Vessel.
#Range: > 64
materiaVesselAdmixtureCapacity = 1800
#The amount of time, in ticks, a Deluge Purifier goes between drawing more Eldrin power.
#Range: 1 ~ 6000
delugePurifierOperationTime = 300
#The amount of Water and Steam, in mB, the Deluge Purifier's internal tanks can hold.
#Range: > 500
delugePurifierTankCapacity = 2000
#The amount of time, in ticks, an Inferno Engine goes between drawing more Eldrin power.
#Range: 1 ~ 6000
infernoEngineOperationTime = 300
#The amount of Smoke, in mB, the Inferno Engine's internal tank can hold.
#Range: > 500
infernoEngineTankCapacity = 2000
#The amount of time, in ticks, a Quake Refinery goes between drawing more Eldrin power.
#Range: 1 ~ 6000
quakeRefineryOperationTime = 300
#The amount of sand that can be stored in the Quake Refinery's internal buffer.
#Range: > 500
quakeRefinerySandCapacity = 16000
#The amount of Grime that can be stored in the Quake Refinery's internal buffer.
#Range: > 500
quakeRefineryGrimeCapacity = 128000
#What percentage of Grime reduced by a Quake Refinery becomes Rarefied Waste instead of Alchemical Waste.
#Range: 1 ~ 100
quakeRefineryRarefiedRate = 20
#The amount of time, in ticks, a Gale Pressurizer goes between drawing more Eldrin power.
#Range: 1 ~ 6000
galePressurizerOperationTime = 300
#The amount of Smoke and Steam, in mB, the Gale Pressurizer's internal tanks can hold.
#Range: > 500
galePressurizerTankCapacity = 2000

