#When enabled some item models are 32x in-hand (Default: true)
#Reload Resourcepacks when joining world (F3+T)
32x = true
#When enabled shows a red vignette on screen corners (Default: true)
#Reload Resourcepacks when joining world (F3+T)
DashOverlay = true
#(Y) Coordinate for Magma Bar
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
MagmaBarY = 5
#(X) Coordinate for Magma Bar
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
MagmaBarX = 4
#Type of Magma Bar
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
#Range: 1 ~ 3
MagmaBarType = 1
#(Y) Coordinate for Mana Bar
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
ManaBarY = 5
#(X) Coordinate for Mana Bar
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
ManaBarX = 4
#Type of Mana Bar
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
#Range: 1 ~ 3
ManaBarType = 1
#(Y) Coordinate for Debuging UI`s
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
DebugY = 0
#(X) Coordinate for Debuging UI`s
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
DebugX = 0

